### ISSUE TITLE
Any connection logs available?

### ISSUE THREAD

**Issue by unintentionalorg** [Ardulink/Ardulink-2#29]
Hi, I'm just starting to look into ardulink. My primary goal is to  use it as a bridge between a cloud based MQTT broker and the board itself (my system is based on Win 10 + an USB connected Arduino Duemilanove). I uploaded the ArduinoProtocol sketch on the board and started the ardulink-mqtt jar. 
On the console I read "INFO: Connected to mqtt broker", but I don't understand if it really works or not: seems like all the commands I tried to send just went unnoticed. 

Is there any log available to investigate what exactly is moved between the board and the ardulink-mqtt running on my PC?

**Comment by LucianoZu** [comment]
Hi,
a way to understand which messages are sent to Arduino is to use our VirtualLink we develop for test issues. In order to use it maybe you have to edit MANIFEST.MF to add the jar in the classpath.

However I think you should set a right -connection option on ardulink-mqtt command line. Default is just ardulink://serial that isn't enough. You should specify at least the connection port. See this article for more detail: http://www.ardulink.org/to-retrieve-an-ardulink-2-link/

Can you post to us your command line options?

**Comment by pfichtner** [comment]
As @LucianoZu mentioned you could use the VirtualLink by passing -connection ardulink://virtual
However: No matter what connection you are using, MqttMain wil log if it sends something to the Link. So if you don't see any message on the terminal this means that has been no message on the topic. 
When using MqttMain's default topic message have to be published on the topic "home/devices/ardulink", e.g. if you wan't to set the value 42 on analog 3 please use home/devices/ardulink/A3/value/set as topic and send 42 as payload (see MqttMain's help when passing -h as argument)

**Comment by pfichtner** [comment]
Closed since no bug and no response
